### ISSUE TITLE
Configure survey?

### ISSUE THREAD

**Issue by BlockByBlock** [AlexisTM/rtk_ros#1]
$ rosrun rtk_ros rtk_node
[FATAL] [1535599984.528776858]: Other serial port exception
[ INFO] [1535599984.528821829]: Connect Driver
[ INFO] [1535599984.528836891]: Configure survey

* I have checked that the serial port is the same at /dev/ttyACM0
* Is the fatal message an error? I have an issue running Ctrl-C to exit the rosrun

**Comment by AlexisTM** [comment]
The fatal error should be a warning, this is still in development and I have no time to consolidate right now. Sorry for that.

Configure survey should be Survey mode configured. It sets the survey duration and the survey accuracy, position of the base station. Once the survey is finished, the RTCM messages will start being published, this could take around 90 seconds.

You should change the log level to debug to ensure it actually speaks to the device. (using rqt_logger_level)

**Comment by BlockByBlock** [comment]
Alright, the debug is throwing `reading more data` for quite a long period, it is probably due to my testing indoor. Tomorrow I will go out and test, I will submit a pull request for dependencies and standalone documentation once I am done. Cheers!

**Comment by AlexisTM** [comment]
Oh, yeah, I only tested outside, you might just not get a fix and that's stuck there. 

Every configurations is handled by PX4/GPS drivers.

Reading more data means the library calls the callback function to have more from the device (could be UART, SPI, Ethernet,...). It should always ask for more data.
