### ISSUE TITLE
GPS_RTK using NTRIP

### ISSUE THREAD

**Issue by ryanyej** [AlexisTM/rtk_ros#2]
hello, after reading mavros GPS_RTK related work, i have more questions about /mavros/gps_rtk/send_rtcm topic
when using NTRIP to get rtcm, then copy rtcm data to /mavros/gps_rtk/send_rtcm topic.
I am not sure to using rtcm data directly received from NTRIP caster
or I need to process these rtcm data first ,then convert to /mavros/gps_rtk/send_rtcm?

**Comment by AlexisTM** [comment]
Hi @ryanyej 
All the processing of this node is handled by GpsDrivers from PX4, to ensure it has the same output as QGroundControl (both QGC & PX4 uses this GpsDrivers library).

I **guess** you _might_ need to use the following code to create the RTCM message buffer.

https://github.com/PX4/PX4-GPSDrivers/blob/master/src/rtcm.cpp

The message splitting to fit Mavlink2 protocol is done in mavros's side, which is reproduced from QGroundControl's implementation.

https://github.com/mavlink/mavros/blob/b0297e39947a4dd6f60213370c864b9139254b37/mavros_extras/src/plugins/gps_rtk.cpp#L77-L115

**Comment by AlexisTM** [comment]
Also, I do not have access to a drone nor an Ublox RTK so I cannot help you more than that.  😞 
Good luck!

**Comment by ryanyej** [comment]
It's OK.
Already helped me a lot.
Thx.
