### ISSUE TITLE
Support M8P

### ISSUE THREAD

**Issue by phinchey** [AlexisTM/rtk_ros#3]
Hi Alexis, thank you for this library, great work!
I'm using a Here3+ GNSS with Ublox M8P.
It's stuck repeating "read more data" without any other debug messages in between.
I can see that the GPS is outputting serial data, it looks like it's in ASCII. Here is a sample:

$GNTXT,01,01,02,ANTSTATUS=OK*25
$GNTXT,01,01,02,PF=379*45
$GNRMC,054323.00,A,4350.13979,N,07906.94004,W,0.025,,191122,,,A*76
$GNVTG,,T,,M,0.025,N,0.046,K,A*38
$GNGGA,054323.00,4350.13979,N,07906.94004,W,1,12,0.85,119.1,M,-35.9,M,,*71
$GNGSA,A,3,19,14,03,06,12,11,24,17,,,,,1.46,0.85,1.19*10
$GNGSA,A,3,69,87,76,85,,,,,,,,,1.46,0.85,1.19*17
$GPGSV,3,1,09,01,05,051,10,03,30,054,37,06,63,236,33,11,26,230,32*76
$GPGSV,3,2,09,12,14,316,17,14,31,154,32,17,59,070,46,19,73,339,20*7B
$GPGSV,3,3,09,24,19,283,17*41
$GLGSV,3,1,10,69,13,026,23,70,22,087,,71,05,132,,75,27,188,*63
$GLGSV,3,2,10,76,60,263,40,77,28,324,,85,44,040,45,86,65,312,31*69
$GLGSV,3,3,10,87,15,258,31,,,,41*57
$GNGLL,4350.13979,N,07906.94004,W,054323.00,A,A*60

Does your library support this kind of input?

**Comment by AlexisTM** [comment]
This node is barely an overlay over PX4/GpsDrivers outside of QGroundControl.
Sadly, it has gone unmaintained for 4 years as I do not have any hardware to test it anymore. 

You could try to update the GpsDrivers submodule to newer versions.

**Comment by phinchey** [comment]
Ok, I'll try that, and thanks again for your sharing your work!

**Comment by phinchey** [comment]
Yes it worked! Thanks!!
For anyone in the future who wants to use a RTK ground unit that is supported by PX4 or Ardupilot that was released after the last commit of this repo, simply do this:

git submodule update --remote --merge

And then it works perfectly

**Comment by AlexisTM** [comment]
Could you make a PR? I would be happy to merge it ;) 
And thank you for testing!
