### ISSUE TITLE
Got stuck at while loop

### ISSUE THREAD

**Issue by gitsr-sys** [AlexisTM/rtk_ros#4]
@AlexisTM 

Hello,
I know this is an old abandoned package, but I have a quick question regarding the code..

When I ran the node (`rosrun rtk_ros rtk_node`), the code got stuck at the `while` loop
[https://github.com/AlexisTM/GpsDrivers/blob/master/src/ubx.cpp#L431](https://github.com/AlexisTM/GpsDrivers/blob/master/src/ubx.cpp#L440)
during `GPSDriverUBX::configure(unsigned &baudrate, OutputMode output_mode)` [https://github.com/AlexisTM/GpsDrivers/blob/master/src/ubx.cpp#L107](https://github.com/AlexisTM/GpsDrivers/blob/master/src/ubx.cpp#L107) which is ran by the line [https://github.com/AlexisTM/rtk_ros/blob/master/rtk_ros/include/rtk_ros/rtk_node.hpp#L102](https://github.com/AlexisTM/rtk_ros/blob/master/rtk_ros/include/rtk_ros/rtk_node.hpp#L102)

Is it your intention...?
I seems like not working correctly for the `while` loop..

I know you are busy, but please have a look for seconds... and please let me know..

Thank you in advance..

**Comment by AlexisTM** [comment]
Hey, this is the configuration step, solely handled by the gpsdrivers library from https://github.com/PX4/PX4-GPSDrivers

I suppose there is a serial communication issue with your GPS device as it is supposed to return from the while(true) once the data is received. I generally use [interceptty](https://github.com/geoffmeyers/interceptty) to check the serial traffic live.

Regardless, I would suggest you to first update the gpsdrivers library, it has come from a long way over 6 years.

**Comment by gitsr-sys** [comment]
@AlexisTM 
Thank you for your answer.
I had a look `GPSDriverUBX::receive(unsigned timeout)` block, and it seems there is no change... the while loop logic seems the same with yours..

Do you think it can be out of `while(true)` with `return handled`??
[https://github.com/AlexisTM/GpsDrivers/blob/master/src/ubx.cpp#L477](https://github.com/AlexisTM/GpsDrivers/blob/master/src/ubx.cpp#L477)

**Comment by AlexisTM** [comment]
Yes, it does go out of the while(true) with it.

**Comment by gitsr-sys** [comment]
@AlexisTM 
Is there any plan to convert this package for ROS2?

**Comment by AlexisTM** [comment]
It should be trivial to convert it to ROS 2. But unless I happen to have the hardware to achieve some tests for it, I won't do it. While trivial, it is also trivial to break it if it is untested.

Note the PX4 Drivers libraries have to be updated.

**Comment by AlexisTM** [comment]
Closing as stale
